### ISSUE TITLE
Minor UI updates to Coverage chart

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-cht-demo#90]
- [x] Add X-axis label "Date Signal Reported"
- [x] Add Y-axis label "Signals"
- [x] Change "signals reported" to just be "Reported"
- [x] Update series legend labels to be capitalized (Investigated, Reported, Verified)  
- [ ] If possible, update the order of the series labels so that it's Reported, Verified, Investigated
- [x] Default the time grain to be by "Month"
- [x] If it's possible to control it, the X-axis ticks should be formatted just as the Month name (see below)

<img width="535" alt="Screen Shot 2020-06-26 at 4 23 03 PM" src="https://user-images.githubusercontent.com/10096985/85897933-545e5800-b7c9-11ea-8946-7f0ac9342513.png">

**Comment by Pall-v** [comment]
I wasn't able to find a way to change the order of the series labels.  They default to alphabetical. There are some open issues related to this on GitHub for other chart types.
