### ISSUE TITLE
Minor UI updates to Signals Reported chart

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-cht-demo#91]
- [x] Update the name name of the chart to be `Signals Reported vs. Signals Verified as a Public Health Threat`
- [x] Default the time grain to be by "Month" instead of day
- [x] Update the X-axis ticks to be formatted just as the month name (see below, like it is for % of Reported....)

<img width="535" alt="Screen Shot 2020-06-26 at 4 23 03 PM" src="https://user-images.githubusercontent.com/10096985/85897933-545e5800-b7c9-11ea-8946-7f0ac9342513.png">

**Comment by tsengtammy** [comment]
The adaptative x axis formatting for this bar chart is a little bit odd - it won't display every month (although you can see the month if you hover over the bars). The alternative is ticks that say '2019/10/01, 2020/01/01' etc.

**Comment by michaelkohn** [comment]
Decided to leave as is for now. Bar and line charts unfortunately deal with this a little differently.
