### ISSUE TITLE
Explore options for color_scheme

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-cht-demo#93]
Ideally we'd create a CHT color_scheme, but it sounds like usage of colors in the color_scheme is inconsistent.  In light of that, we should try to figure out how to explicitly set colors for series data (lines, bars, etc....)

For now, we can simply choose some colors from existing CHT resources and hard code those for each of the series in each of the charts.

HEX and RGB can be found here https://docs.communityhealthtoolkit.org/design/core/#primary-colors and perhaps we can just use Blue, Pink, and Yellow for each chart. So if the chart only has 1 series, make it blue. If the chart has 2 series, make them Blue and Pink, and if there are three, use Blue, Pink, and Yellow.  (I'm fine with other colors if you prefer another scheme).

**Comment by michaelkohn** [comment]
FWIW... I noticed you can set the color scheme at the dashboard level (vs. individual charts). I imagine it just gives each series the next up color in the scheme, not sure if it just cycles back around if there are more series than colors in your scheme... maybe it just gives you random.

The LYFT color scheme looks better than AirBnB :-) 

![Screen Shot 2020-06-26 at 5 13 03 PM](https://user-images.githubusercontent.com/10096985/85901784-858e5680-b7d0-11ea-921c-12114cf5d194.png)

**Comment by Pall-v** [comment]
- Looks like the dashboard color scheme is consistent across charts. For example, the "Reported" series and "Threat Exists" series both get the same color in both charts that they appear in.
- I manually assigned colors to the Coverage plot via json as an example.
- We can manually assign colors via json at the dashboard level also. I think this would be the best method if the dashboard color scheme behavior doesn't meet our needs.

**Comment by michaelkohn** [comment]
Thanks @Pall-v .  Let's go ahead and set it at the dashboard level and use the color scheme / colors mentioned at the top, ie

> HEX and RGB can be found here https://docs.communityhealthtoolkit.org/design/core/#primary-colors and perhaps we can just use Blue, Pink, and Yellow for each chart. So if the chart only has 1 series, make it blue. If the chart has 2 series, make them Blue and Pink, and if there are three, use Blue, Pink, and Yellow. (I'm fine with other colors if you prefer another scheme).

**Comment by Pall-v** [comment]
Updated using four primary colors from the CHT color_scheme.

**Comment by michaelkohn** [comment]
Looks like the *Coverage* chart is still using different colors. Maybe you can show us how to change this during the call today.

![Screen Shot 2020-07-17 at 12 57 08 PM](https://user-images.githubusercontent.com/10096985/87811825-3c5c8000-c82d-11ea-8efb-655adc945eb1.png)
