### ISSUE TITLE
Explore adding a date filter to the EBS dashboard

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-cht-demo#94]
This might look like the filter on the [World Health example dashboard](https://superset.dev.medicmobile.org/superset/dashboard/world_health/).  The goal is to have it control all the other widgets on the dashboard.

Can also experiment with adding the slider-like thing under the charts, like what you see when you "explore chart". 

![Screen Shot 2020-06-26 at 5 26 35 PM](https://user-images.githubusercontent.com/10096985/85902516-347f6200-b7d2-11ea-80cc-f00ff118d874.png)

![Screen Shot 2020-06-26 at 5 30 02 PM](https://user-images.githubusercontent.com/10096985/85902715-afe11380-b7d2-11ea-826d-11a475597bd7.png)

**Comment by tsengtammy** [comment]
@Pall-v - when I was adding the filter box for 'Facility', 'Date' was one of the default filter options so I added it to the box. I didn't do anything other than add the default filter though, so you can explore the other options (e.g. they had granularity options).

**Comment by Pall-v** [comment]
- added a time grain filter.
-  Added sliders to Coverage and % of Reported Signals Verified charts. Not sure if we want these sliders to propagate to the other charts (there is a propagate option but it did not work as I expected)

**Comment by michaelkohn** [comment]
@Pall-v as discussed, can we see if it's possible to add the little filter icon like it shows for the others? 

![Screen Shot 2020-07-12 at 10 29 45 AM](https://user-images.githubusercontent.com/10096985/87249057-df2a8e00-c42a-11ea-8a02-44745b3b0806.png)

**Comment by Pall-v** [comment]
I wasn't able to find a way to change this or any related documentation. Also, this will be less relevant if we ever have more than 3 filters because, in that scenario, it collapses the charts' filter icons to a single icon per chart.
