### ISSUE TITLE
Explore adding a facility filter on EBS dashboard

### ISSUE THREAD

**Issue by michaelkohn** [medic/config-cht-demo#95]
This might look like the filter on the [World Health example dashboard](https://superset.dev.medicmobile.org/superset/dashboard/world_health/).  The goal is to have it control all the other widgets on the dashboard.

![Screen Shot 2020-06-26 at 5 26 35 PM](https://user-images.githubusercontent.com/10096985/85904697-66df8e00-b7d7-11ea-9c5d-ef7df4f391a9.png)

I've added the `facility` field (and data) to `superset_signal_view` already.  You might have to add it to the "Table" in Superset as well, since the field was added after the table was added to SS.

Ideally we'd have options for ALL and any facility found in that field.

![Screen Shot 2020-06-26 at 5 32 52 PM](https://user-images.githubusercontent.com/10096985/85904732-7bbc2180-b7d7-11ea-8321-78ef0e079dc6.png)

**Comment by tsengtammy** [comment]
Done! It's not quite the same as the screenshot, but by default (no filters applied) all facilities are shown, and you can filter on any combination of facilities (filtering on all 3 = the same as no filter).
